.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VOLUMEICON 1 "July 2, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
volumeicon \- lightweight ALSA volume icon for the systray
.SH SYNOPSIS
.B volumeicon
.SH DESCRIPTION
.B volumeicon
provides a system tray icon for managing the ALSA mixer. It should
be run in the background of an X session with an available systray.
.SH OPTIONS
No options are available.
.SH AUTHOR
volumeicon was written by Maato <maato@softwarebakery.com>.
.PP
This manual page was written by Andrew Gainer <gainer.andrew@gmail.com>,
for the Debian project (and may be used by others).
